/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Movimiento;

import ConsultarReporte.*;
import java.awt.Component;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author saaii
 */
public class Ref_emp extends javax.swing.JPanel {

    /**
     * Creates new form Ref_emp
     */
    ConsultasMov a=new ConsultasMov();
    public Ref_emp() {
        initComponents();
        jPanel1.setOpaque(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        Renovacion = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Prestamo = new javax.swing.JTextField();
        Finiquito = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Refrendar Empeño");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setForeground(java.awt.Color.white);
        jLabel3.setText("idEmpeño: ");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, -1, -1));

        id.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 150, 100, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 150, -1, -1));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Renovacion.setEditable(false);
        Renovacion.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel1.add(Renovacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 40, 140, -1));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel6.setForeground(java.awt.Color.white);
        jLabel6.setText("Renovación");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, -1, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel5.setForeground(java.awt.Color.white);
        jLabel5.setText("Prestamo");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        Prestamo.setEditable(false);
        Prestamo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel1.add(Prestamo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 140, -1));

        Finiquito.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel1.add(Finiquito, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 40, 140, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel4.setForeground(java.awt.Color.white);
        jLabel4.setText("Finiquito");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 10, -1, -1));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton3.setText("Retiro");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 170, -1, -1));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setText("Renovación");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 170, -1, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 680, 220));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo.jpg"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if("Pendiente".equals(a.Consulta1emp(id.getText())[5])|"No Renovado".equals(a.Consulta1emp(id.getText())[5])){
           RegistroMov r=new RegistroMov();
       Fecha fh=new Fecha();
      Calendar calendar = Calendar.getInstance();
      Date fechafin=fh.fechastringadateformat(a.Consulta1emp(id.getText())[4]);
      calendar.setTime(fechafin);
      calendar.add(Calendar.MONTH,1);
      fechafin=calendar.getTime();
      int renovaciontot=Integer.parseInt(a.Consulta1emp(id.getText())[1]);
      int precio=Integer.parseInt(a.Consulta1emp(id.getText())[0]);
      int renovar=renovaciontot+(precio/5);
      r.RefEmp(id.getText(),String.valueOf(renovar),fh.fechadateastring(fechafin));
       id.setText("");
       Prestamo.setText("");
       Renovacion.setText("");
       Finiquito.setText(""); 
        }
        else{
            JOptionPane.showMessageDialog(null,"Este empeño ya se ha renovado o ya se retiró el articulo");
            for(Component c:jPanel1.getComponents()){
                c.setEnabled(false);
           }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int prestamo=Integer.parseInt(a.Consulta1emp(id.getText())[0]);
        int renovacion,finiquito;
        Fecha fh=new Fecha();
        Prestamo.setEnabled(true);
        Renovacion.setEnabled(true);
        Finiquito.setEnabled(true);
        Prestamo.setText("");
        Renovacion.setText("");
        Finiquito.setText("");
        if(a.Consulta1emp(id.getText())==null){
        id.setText("");
        }
        else{
        Calendar calendar = Calendar.getInstance();
        Date fechafin=fh.fechastringadateformat(a.Consulta1emp(id.getText())[4]);
        Date    fecha1,fecha2,fechaactual;
        fechaactual=fh.fechastringadateformat(fh.fechaActual());
        calendar.setTime(fechafin);
        calendar.add(Calendar.MONTH,-1);
        calendar.add(Calendar.DAY_OF_YEAR,-1);
        fecha1=calendar.getTime();
        calendar.add(Calendar.DAY_OF_YEAR,7);
        fecha2=calendar.getTime();
        if(fechaactual.after(fecha1)&&fechaactual.before(fecha2)){
          renovacion=prestamo/5; 
          finiquito=prestamo;
        Prestamo.setText(String.valueOf(prestamo));
        Renovacion.setText(String.valueOf(renovacion));
        Finiquito.setText(String.valueOf(finiquito));
        if(a.Consulta1emp(id.getText())[5].equals("Retirado")){
           JOptionPane.showMessageDialog(null,"El empeño se concretó correctamente");
           for(Component c:jPanel1.getComponents()){
                c.setEnabled(false);
           }
        }
        }
        //
        else{
        renovacion=prestamo/5;
        finiquito=renovacion+prestamo;
        Prestamo.setText(String.valueOf(prestamo));
        Renovacion.setText(String.valueOf(renovacion));
        Finiquito.setText(String.valueOf(finiquito));
        if(a.Consulta1emp(id.getText())[5].equals("Retirado")){
           JOptionPane.showMessageDialog(null,"El empeño se concretó correctamente");
           for(Component c:jPanel1.getComponents()){
                c.setEnabled(false);
           }
        }
        }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if("Retirado".equals(a.Consulta1emp(id.getText())[5])){
          JOptionPane.showMessageDialog(null,"El empeño ya se ha concretado");  
         for(Component c:jPanel1.getComponents()){
                c.setEnabled(false);
           }
        }
        else{
            RegistroMov r=new RegistroMov();
        r.RetiroEmp(id.getText(),Finiquito.getText());
        id.setText("");
       Prestamo.setText("");
       Renovacion.setText("");
       Finiquito.setText("");
        }
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Finiquito;
    private javax.swing.JTextField Prestamo;
    private javax.swing.JTextField Renovacion;
    private javax.swing.JTextField id;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
