/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Movimiento;

import Almacen.Consultas;
import ConsultarReporte.ConsultasMov;
import java.awt.Component;
import javax.swing.JOptionPane;

/**
 *
 * @author saaii
 */
public class Ref_Aprt extends javax.swing.JPanel {

    /**
     * Creates new form Ref_Aprt
     */
    ConsultasMov a=new ConsultasMov();
    public Ref_Aprt() {
        initComponents();
        jPanel1.setOpaque(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        pagado = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        restante = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        refrendar = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Refrendar Apartado");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setForeground(java.awt.Color.white);
        jLabel3.setText("idApartado: ");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 150, -1, -1));

        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 150, 70, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 150, -1, -1));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setText("Refrendar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 450, -1, -1));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pagado.setEditable(false);
        pagado.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel1.add(pagado, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 140, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel5.setForeground(java.awt.Color.white);
        jLabel5.setText("Pagado:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel6.setForeground(java.awt.Color.white);
        jLabel6.setText("Restante:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, -1, -1));

        restante.setEditable(false);
        restante.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel1.add(restante, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 50, 140, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel4.setForeground(java.awt.Color.white);
        jLabel4.setText("Por refrendar:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 20, -1, -1));

        refrendar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel1.add(refrendar, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 50, 140, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 680, 90));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo.jpg"))); // NOI18N
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        jTextField1.setEnabled(true);
        pagado.setEnabled(true);
        restante.setEnabled(true);
        refrendar.setEnabled(true);
        if(a.Consulta1apart(jTextField1.getText())!=null){
        int restante1=Integer.parseInt(a.Consulta1apart(jTextField1.getText())[0])-Integer.parseInt(a.Consulta1apart(jTextField1.getText())[1]);
        pagado.setText(a.Consulta1apart(jTextField1.getText())[1]);
        restante.setText(String.valueOf(restante1));
        
        if(restante1==0){
           JOptionPane.showMessageDialog(null,"El apartado se concretó correctamente");
           for(Component c:jPanel1.getComponents()){
                c.setEnabled(false);
            }
        }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        RegistroMov r=new RegistroMov();
        r.RefAprt(jTextField1.getText(), String.valueOf(Integer.parseInt(refrendar.getText())+Integer.parseInt(pagado.getText())));
        Consultas con=new Consultas();
        con.actualizart(a.Consulta1apart(jTextField1.getText())[3]);
        jTextField1.setText("");
        pagado.setText("");
        restante.setText("");
        refrendar.setText("");
        
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField pagado;
    private javax.swing.JTextField refrendar;
    private javax.swing.JTextField restante;
    // End of variables declaration//GEN-END:variables
}
