/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package casadeempeños;


import ConsultarReporte.Consultar_Reporte;
import Almacen.Almacen;
import ConsultarCliente.AgregarCuenta;
import Movimiento.*;
import java.awt.*;
import java.awt.event.KeyEvent;
import net.sf.jcarrierpigeon.Notification;
import net.sf.jcarrierpigeon.NotificationQueue;
import net.sf.jcarrierpigeon.WindowPosition;
import org.jvnet.substance.SubstanceLookAndFeel;



/**
 *
 * @author Gerardo
 */
public class Pantalla_bienvenido extends javax.swing.JFrame {

    /**
     * Creates new form Pantalla_bienvenido
     */
    
    NotificaconesSQL n=new NotificaconesSQL();
    Fecha fh=new Fecha();
    LittleNotification noti=new LittleNotification();
    Notification obj=new Notification(noti,WindowPosition.BOTTOMRIGHT,0,0,5000);
    public Pantalla_bienvenido() {
       
        initComponents();
        Image icon = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Imagenes/LOGO.png"));
       setIconImage(icon);
        
        cuenta1.setText(Inicio_sesion.cuenta);
        int filas1=n.ConsultaEmpeñosfecha(fh.fechaActual()).getRowCount();
        int filas2=n.ConsultaApartadosfecha(fh.fechaActual()).getRowCount();
        if(filas1>0|filas2>0){
            NotificationQueue val=new NotificationQueue();
            val.add(obj);
        }
        
    }
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cuenta1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        Movimiento = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        Almacen = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        Consulta_reporte = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Money Max");
        setBackground(new java.awt.Color(51, 0, 51));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(550, 500));
        setMinimumSize(new java.awt.Dimension(550, 500));
        setName("Pantalla Bienvenido"); // NOI18N
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(550, 500));
        setResizable(false);
        getContentPane().setLayout(null);

        cuenta1.setBackground(new java.awt.Color(0, 0, 52));
        cuenta1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        cuenta1.setForeground(new java.awt.Color(255, 255, 255));
        cuenta1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(cuenta1);
        cuenta1.setBounds(370, 30, 170, 30);

        jLabel1.setBackground(new java.awt.Color(255, 0, 255));
        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Bienvenido, ¿Qué desea realizar?");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 10, 340, 30);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setText("Cerrar Sesión");
        jButton2.setBorder(null);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jButton2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton2KeyPressed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(410, 60, 100, 30);

        jPanel2.setBackground(new java.awt.Color(0, 0, 52));
        jPanel2.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Movimiento.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Movimiento.setForeground(new java.awt.Color(255, 255, 255));
        Movimiento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/movimiento2.png"))); // NOI18N
        Movimiento.setText("Movimiento");
        Movimiento.setBorder(null);
        Movimiento.setBorderPainted(false);
        Movimiento.setContentAreaFilled(false);
        Movimiento.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Movimiento.setFocusPainted(false);
        Movimiento.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Movimiento.setIconTextGap(-3);
        Movimiento.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/movimiento3.png"))); // NOI18N
        Movimiento.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/movimiento1.png"))); // NOI18N
        Movimiento.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        Movimiento.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Movimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MovimientoActionPerformed(evt);
            }
        });
        jPanel2.add(Movimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 140, 100));

        getContentPane().add(jPanel2);
        jPanel2.setBounds(80, 110, 190, 170);

        jPanel3.setBackground(new java.awt.Color(0, 0, 52));
        jPanel3.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Almacen.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Almacen.setForeground(new java.awt.Color(255, 255, 255));
        Almacen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/almacen2.png"))); // NOI18N
        Almacen.setText("Almacen");
        Almacen.setBorder(null);
        Almacen.setBorderPainted(false);
        Almacen.setContentAreaFilled(false);
        Almacen.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Almacen.setFocusPainted(false);
        Almacen.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Almacen.setIconTextGap(-3);
        Almacen.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/almacen3.png"))); // NOI18N
        Almacen.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/almacen1.png"))); // NOI18N
        Almacen.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        Almacen.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Almacen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlmacenActionPerformed(evt);
            }
        });
        jPanel3.add(Almacen, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 140, 100));

        getContentPane().add(jPanel3);
        jPanel3.setBounds(280, 110, 180, 170);

        jPanel4.setBackground(new java.awt.Color(0, 0, 52));
        jPanel4.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Consulta_reporte.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Consulta_reporte.setForeground(new java.awt.Color(255, 255, 255));
        Consulta_reporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/reporte2.png"))); // NOI18N
        Consulta_reporte.setText("Consulta reporte");
        Consulta_reporte.setBorder(null);
        Consulta_reporte.setBorderPainted(false);
        Consulta_reporte.setContentAreaFilled(false);
        Consulta_reporte.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Consulta_reporte.setFocusPainted(false);
        Consulta_reporte.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Consulta_reporte.setIconTextGap(-3);
        Consulta_reporte.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/reporte3.png"))); // NOI18N
        Consulta_reporte.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/reporte1.png"))); // NOI18N
        Consulta_reporte.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        Consulta_reporte.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Consulta_reporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Consulta_reporteActionPerformed(evt);
            }
        });
        jPanel4.add(Consulta_reporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 140, 100));

        getContentPane().add(jPanel4);
        jPanel4.setBounds(80, 290, 190, 170);

        jPanel5.setBackground(new java.awt.Color(0, 0, 52));
        jPanel5.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cuenta2.png"))); // NOI18N
        jButton1.setText("Cuentas");
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setFocusPainted(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cuenta3.png"))); // NOI18N
        jButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cuenta1.png"))); // NOI18N
        jButton1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 160, -1));

        getContentPane().add(jPanel5);
        jPanel5.setBounds(280, 290, 180, 170);

        jButton4.setText("Tema Gris");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(10, 50, 90, 25);

        jButton5.setText("Tema Claro");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(110, 50, 90, 25);

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo.jpg"))); // NOI18N
        jLabelFondo.setMaximumSize(new java.awt.Dimension(440, 390));
        jLabelFondo.setMinimumSize(new java.awt.Dimension(440, 390));
        jLabelFondo.setPreferredSize(new java.awt.Dimension(440, 390));
        getContentPane().add(jLabelFondo);
        jLabelFondo.setBounds(0, 0, 550, 480);

        getAccessibleContext().setAccessibleDescription("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void MovimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MovimientoActionPerformed
        //declara la clase de movimiento como un objeto y despues lo vuelve visible
        this.dispose();
         Movimientos mov = new Movimientos();
         mov.setVisible(true);
    }//GEN-LAST:event_MovimientoActionPerformed

    private void Consulta_reporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Consulta_reporteActionPerformed
        //declara la clase de consultar_reporte como un objeto y despues lo vuelve visible
        this.dispose();
        Consultar_Reporte Crep=new Consultar_Reporte();
        Crep.setVisible(true);
    }//GEN-LAST:event_Consulta_reporteActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
        AgregarCuenta agc =new AgregarCuenta();
      agc.setVisible(true);
      
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       this.dispose();
       Iniciocuentas2 inicio =new Iniciocuentas2();
       inicio.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton2KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
           this.dispose();
       Iniciocuentas2 inicio =new Iniciocuentas2();
       inicio.setVisible(true); 
        }
    }//GEN-LAST:event_jButton2KeyPressed

    private void AlmacenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlmacenActionPerformed
        this.dispose();
        Almacen almacen =new Almacen();
        almacen.setVisible(true);
    }//GEN-LAST:event_AlmacenActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        Pantalla_bienvenido.setDefaultLookAndFeelDecorated(false);
        SubstanceLookAndFeel.setSkin("org.jvnet.substance.skin.MagmaSkin");
        SubstanceLookAndFeel.setCurrentTheme("org.jvnet.substance.theme.SubstanceEbonyTheme");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        Pantalla_bienvenido.setDefaultLookAndFeelDecorated(false);
        SubstanceLookAndFeel.setSkin("org.jvnet.substance.skin.MagmaSkin");
        SubstanceLookAndFeel.setCurrentTheme("org.jvnet.substance.theme.SubstanceSteelBlueTheme");
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
  
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Almacen;
    private javax.swing.JButton Consulta_reporte;
    private javax.swing.JButton Movimiento;
    public static javax.swing.JLabel cuenta1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    // End of variables declaration//GEN-END:variables
}
