/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ConsultarReporte;

import casadeempeños.Pantalla_bienvenido;
import java.awt.*;

/**
 *
 * @author Gerardo
 */
public class Consultar_Reporte extends javax.swing.JFrame {

    /**
     * Creates new form Consultar_Reporte
     */
    public Consultar_Reporte() {
        initComponents();
                Image icon = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Imagenes/LOGO.png"));
       setIconImage(icon);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtoncompras = new javax.swing.JButton();
        jButtonventas = new javax.swing.JButton();
        jButtonempeños = new javax.swing.JButton();
        jButtonapartados = new javax.swing.JButton();
        jButtonperdiganancias = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabelfondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Consulta/Reporte");
        setMaximumSize(new java.awt.Dimension(421, 405));
        setMinimumSize(new java.awt.Dimension(421, 405));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(426, 425));
        setResizable(false);
        getContentPane().setLayout(null);

        jButtoncompras.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButtoncompras.setForeground(new java.awt.Color(255, 255, 255));
        jButtoncompras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/compra2.png"))); // NOI18N
        jButtoncompras.setText("Compras");
        jButtoncompras.setBorder(null);
        jButtoncompras.setBorderPainted(false);
        jButtoncompras.setContentAreaFilled(false);
        jButtoncompras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtoncompras.setFocusPainted(false);
        jButtoncompras.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtoncompras.setIconTextGap(-3);
        jButtoncompras.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/compra3.png"))); // NOI18N
        jButtoncompras.setRequestFocusEnabled(false);
        jButtoncompras.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/compra1.png"))); // NOI18N
        jButtoncompras.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButtoncompras.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtoncompras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtoncomprasActionPerformed(evt);
            }
        });
        getContentPane().add(jButtoncompras);
        jButtoncompras.setBounds(70, 80, 80, 96);

        jButtonventas.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButtonventas.setForeground(new java.awt.Color(255, 255, 255));
        jButtonventas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/venta2.png"))); // NOI18N
        jButtonventas.setText("Ventas");
        jButtonventas.setBorder(null);
        jButtonventas.setBorderPainted(false);
        jButtonventas.setContentAreaFilled(false);
        jButtonventas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonventas.setFocusPainted(false);
        jButtonventas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonventas.setIconTextGap(-3);
        jButtonventas.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/venta3.png"))); // NOI18N
        jButtonventas.setRequestFocusEnabled(false);
        jButtonventas.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/venta1.png"))); // NOI18N
        jButtonventas.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButtonventas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonventas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonventasActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonventas);
        jButtonventas.setBounds(280, 80, 85, 96);

        jButtonempeños.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButtonempeños.setForeground(new java.awt.Color(255, 255, 255));
        jButtonempeños.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/empeño2.png"))); // NOI18N
        jButtonempeños.setText("Empeños");
        jButtonempeños.setBorder(null);
        jButtonempeños.setBorderPainted(false);
        jButtonempeños.setContentAreaFilled(false);
        jButtonempeños.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonempeños.setFocusPainted(false);
        jButtonempeños.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonempeños.setIconTextGap(-3);
        jButtonempeños.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/empeño3.png"))); // NOI18N
        jButtonempeños.setRequestFocusEnabled(false);
        jButtonempeños.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/empeño1.png"))); // NOI18N
        jButtonempeños.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButtonempeños.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonempeños.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonempeñosActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonempeños);
        jButtonempeños.setBounds(60, 280, 80, 96);

        jButtonapartados.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButtonapartados.setForeground(new java.awt.Color(255, 255, 255));
        jButtonapartados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/apartado2.png"))); // NOI18N
        jButtonapartados.setText("Apartados");
        jButtonapartados.setBorder(null);
        jButtonapartados.setBorderPainted(false);
        jButtonapartados.setContentAreaFilled(false);
        jButtonapartados.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonapartados.setFocusPainted(false);
        jButtonapartados.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonapartados.setIconTextGap(-3);
        jButtonapartados.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/apartado3.png"))); // NOI18N
        jButtonapartados.setRequestFocusEnabled(false);
        jButtonapartados.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/apartado1.png"))); // NOI18N
        jButtonapartados.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButtonapartados.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonapartados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonapartadosActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonapartados);
        jButtonapartados.setBounds(280, 280, 80, 96);

        jButtonperdiganancias.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButtonperdiganancias.setForeground(new java.awt.Color(255, 255, 255));
        jButtonperdiganancias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/perdgng2.png"))); // NOI18N
        jButtonperdiganancias.setBorder(null);
        jButtonperdiganancias.setBorderPainted(false);
        jButtonperdiganancias.setContentAreaFilled(false);
        jButtonperdiganancias.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonperdiganancias.setFocusPainted(false);
        jButtonperdiganancias.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonperdiganancias.setIconTextGap(-3);
        jButtonperdiganancias.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/perdgng3.png"))); // NOI18N
        jButtonperdiganancias.setRequestFocusEnabled(false);
        jButtonperdiganancias.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/perdgng.png"))); // NOI18N
        jButtonperdiganancias.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButtonperdiganancias.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonperdiganancias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonperdigananciasActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonperdiganancias);
        jButtonperdiganancias.setBounds(150, 170, 150, 90);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Perdidas/Ganancias");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(150, 230, 150, 40);

        jButton1.setBackground(new java.awt.Color(96, 3, 3));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Go-back-icon (Custom).png"))); // NOI18N
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(370, 0, 50, 50);

        jLabelfondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo.jpg"))); // NOI18N
        jLabelfondo.setMaximumSize(new java.awt.Dimension(421, 405));
        jLabelfondo.setMinimumSize(new java.awt.Dimension(421, 405));
        jLabelfondo.setPreferredSize(new java.awt.Dimension(421, 405));
        getContentPane().add(jLabelfondo);
        jLabelfondo.setBounds(0, 0, 421, 405);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtoncomprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtoncomprasActionPerformed
       Reportecompras rcompras=new Reportecompras();
       this.dispose();
       rcompras.setVisible(true);
       
    }//GEN-LAST:event_jButtoncomprasActionPerformed

    private void jButtonventasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonventasActionPerformed
        Reporteventas rventas=new  Reporteventas();
        this.dispose();
        rventas.setVisible(true);
    }//GEN-LAST:event_jButtonventasActionPerformed

    private void jButtonempeñosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonempeñosActionPerformed
reporteempeños rempeños=new reporteempeños();
this.dispose();
rempeños.setVisible(true);
    }//GEN-LAST:event_jButtonempeñosActionPerformed

    private void jButtonapartadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonapartadosActionPerformed
Reporteapartados rapartados=new Reporteapartados();
this.dispose();
rapartados.setVisible(true);
    }//GEN-LAST:event_jButtonapartadosActionPerformed

    private void jButtonperdigananciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonperdigananciasActionPerformed
       this.dispose();
        Reporteperdidas rpg =new Reporteperdidas();
        rpg.setVisible(true);
    }//GEN-LAST:event_jButtonperdigananciasActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        Pantalla_bienvenido pbien = new Pantalla_bienvenido();
        pbien.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonapartados;
    private javax.swing.JButton jButtoncompras;
    private javax.swing.JButton jButtonempeños;
    private javax.swing.JButton jButtonperdiganancias;
    private javax.swing.JButton jButtonventas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelfondo;
    // End of variables declaration//GEN-END:variables
}
