/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ConsultarReporte;

import Movimiento.ModificaMov;
import java.awt.Image;
import java.awt.Toolkit;
import java.text.SimpleDateFormat;

/**
 *
 * @author Gerardo
 */
public class reporteempeños extends javax.swing.JFrame {

    /**
     * Creates new form Reportecompras
     */
    ConsultasMov a=new ConsultasMov();
    public reporteempeños() {
        initComponents();
                Image icon = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Imagenes/LOGO.png"));
       setIconImage(icon);
        setVisible(true);
        
        TablaEmpeños.setModel(a.ConsultaEmpeños());
        SumasMov suma=new SumasMov();
        totalprestamos.setText("$"+suma.Suma_prestEmpeños());
        totalrefrendos.setText("$"+suma.Suma_refEmpeños());
        jPanel1.setOpaque(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonatras = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        Fecha2 = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaEmpeños = new javax.swing.JTable();
        totalprestamos = new javax.swing.JTextField();
        jLabel = new javax.swing.JLabel();
        totalrefrendos = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        Fecha1 = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        fechaini = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        fechafin = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        finiquito = new javax.swing.JTextField();
        renovacion = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        prestamo = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        cliente = new javax.swing.JTextField();
        empleado = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        estado = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        articulo = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabelfondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Consulta reporte de compras");
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonatras.setBackground(new java.awt.Color(96, 3, 3));
        jButtonatras.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonatras.setForeground(new java.awt.Color(255, 255, 255));
        jButtonatras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Go-back-icon (Custom).png"))); // NOI18N
        jButtonatras.setBorderPainted(false);
        jButtonatras.setContentAreaFilled(false);
        jButtonatras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonatrasActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonatras, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("al:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 30, 40, -1));

        Fecha2.setBackground(new java.awt.Color(96, 3, 3));
        getContentPane().add(Fecha2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 30, 110, -1));

        TablaEmpeños.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        TablaEmpeños.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaEmpeñosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TablaEmpeños);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 800, 390));

        totalprestamos.setEditable(false);
        totalprestamos.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(totalprestamos, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 470, 110, -1));

        jLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel.setForeground(java.awt.Color.white);
        jLabel.setText("Total de prestamos:");
        getContentPane().add(jLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 470, 130, -1));

        totalrefrendos.setEditable(false);
        totalrefrendos.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(totalrefrendos, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 470, 120, -1));

        jButton1.setBackground(new java.awt.Color(96, 3, 3));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("Aceptar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 30, -1, -1));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Fecha de reporte del:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 170, -1));

        Fecha1.setBackground(new java.awt.Color(96, 3, 3));
        getContentPane().add(Fecha1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 110, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(java.awt.Color.white);
        jLabel1.setText("Total de refrendos:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 470, -1, -1));

        jPanel1.setBackground(new java.awt.Color(0, 0, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("idEmpeño:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 90, 20));

        id.setEditable(false);
        id.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idActionPerformed(evt);
            }
        });
        jPanel1.add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, 130, -1));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Fecha inicial:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 100, 20));

        fechaini.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        fechaini.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fechainiActionPerformed(evt);
            }
        });
        jPanel1.add(fechaini, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 130, -1));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Fecha final:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 90, 20));

        fechafin.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        fechafin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fechafinActionPerformed(evt);
            }
        });
        jPanel1.add(fechafin, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 130, -1));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Finiquito:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 80, 20));

        finiquito.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        finiquito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finiquitoActionPerformed(evt);
            }
        });
        jPanel1.add(finiquito, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 130, -1));

        renovacion.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        renovacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                renovacionActionPerformed(evt);
            }
        });
        jPanel1.add(renovacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, 130, -1));

        jLabel9.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Renovación:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 100, 20));

        jLabel10.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Prestamo:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 80, 20));

        prestamo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        prestamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prestamoActionPerformed(evt);
            }
        });
        jPanel1.add(prestamo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 130, -1));

        jLabel11.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("idCliente:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, 80, 20));

        cliente.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clienteActionPerformed(evt);
            }
        });
        jPanel1.add(cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 280, 130, -1));

        empleado.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        empleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empleadoActionPerformed(evt);
            }
        });
        jPanel1.add(empleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, 130, -1));

        jLabel12.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("idEmpleado:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 90, 20));

        jLabel13.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Estado:");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 80, 20));

        estado.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        estado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estadoActionPerformed(evt);
            }
        });
        jPanel1.add(estado, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 130, -1));

        jLabel14.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("idArticulo:");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, 80, 20));

        articulo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        articulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                articuloActionPerformed(evt);
            }
        });
        jPanel1.add(articulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 310, 130, -1));

        jButton2.setBackground(new java.awt.Color(96, 3, 3));
        jButton2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jButton2.setText("Modificar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 360, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 70, 340, 410));

        jLabelfondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo (Medium).jpg"))); // NOI18N
        jLabelfondo.setText("jLabel1");
        getContentPane().add(jLabelfondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1180, 500));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonatrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonatrasActionPerformed
       this.dispose();
       Consultar_Reporte  con_reporte=new Consultar_Reporte();
       con_reporte.setVisible(true);
    }//GEN-LAST:event_jButtonatrasActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
      TablaEmpeños.setModel(a.ConsultaEmpeñosfecha(new SimpleDateFormat("yyyy-MM-dd").format(Fecha1.getDate()),new SimpleDateFormat("yyyy-MM-dd").format(Fecha2.getDate())));
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idActionPerformed

    private void fechainiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fechainiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fechainiActionPerformed

    private void fechafinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fechafinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fechafinActionPerformed

    private void finiquitoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finiquitoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_finiquitoActionPerformed

    private void renovacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_renovacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_renovacionActionPerformed

    private void prestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prestamoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prestamoActionPerformed

    private void clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clienteActionPerformed

    private void empleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empleadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_empleadoActionPerformed

    private void estadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_estadoActionPerformed

    private void articuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_articuloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_articuloActionPerformed

    private void TablaEmpeñosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaEmpeñosMouseClicked
        // TODO add your handling code here:
        int seleccion=TablaEmpeños.rowAtPoint(evt.getPoint());
        id.setText(String.valueOf(TablaEmpeños.getValueAt(seleccion, 0)));
        fechaini.setText(String.valueOf(TablaEmpeños.getValueAt(seleccion, 1)));
         fechafin.setText(String.valueOf(TablaEmpeños.getValueAt(seleccion, 2)));
          prestamo.setText(String.valueOf(TablaEmpeños.getValueAt(seleccion, 3)));
           renovacion.setText(String.valueOf(TablaEmpeños.getValueAt(seleccion, 4)));
            finiquito.setText(String.valueOf(TablaEmpeños.getValueAt(seleccion, 5)));
             estado.setText(String.valueOf(TablaEmpeños.getValueAt(seleccion, 6)));
              empleado.setText(String.valueOf(TablaEmpeños.getValueAt(seleccion, 7)));
               cliente.setText(String.valueOf(TablaEmpeños.getValueAt(seleccion, 8)));
               articulo.setText(String.valueOf(TablaEmpeños.getValueAt(seleccion, 9)));
    }//GEN-LAST:event_TablaEmpeñosMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         ModificaMov m=new ModificaMov();
         m.ModificaEmpeño(id.getText(), fechaini.getText(), fechafin.getText(), prestamo.getText(), renovacion.getText(), finiquito.getText(), estado.getText(), empleado.getText(), cliente.getText(), articulo.getText());
         TablaEmpeños.setModel(a.ConsultaEmpeños());
         SumasMov suma=new SumasMov();
        totalprestamos.setText("$"+suma.Suma_prestEmpeños());
        totalrefrendos.setText("$"+suma.Suma_refEmpeños());
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser Fecha1;
    private com.toedter.calendar.JDateChooser Fecha2;
    private javax.swing.JTable TablaEmpeños;
    public static javax.swing.JTextField articulo;
    public static javax.swing.JTextField cliente;
    public static javax.swing.JTextField empleado;
    public static javax.swing.JTextField estado;
    public static javax.swing.JTextField fechafin;
    public static javax.swing.JTextField fechaini;
    public static javax.swing.JTextField finiquito;
    public static javax.swing.JTextField id;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonatras;
    private javax.swing.JLabel jLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelfondo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTextField prestamo;
    public static javax.swing.JTextField renovacion;
    private javax.swing.JTextField totalprestamos;
    private javax.swing.JTextField totalrefrendos;
    // End of variables declaration//GEN-END:variables
}
