/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ConsultarReporte;

import Movimiento.ModificaMov;
import java.awt.Image;
import java.awt.Toolkit;
import java.text.SimpleDateFormat;

/**
 *
 * @author Gerardo
 */
public class Reporteapartados extends javax.swing.JFrame {

    /**
     * Creates new form Reportecompras
     */
    ConsultasMov a=new ConsultasMov();
    public Reporteapartados() {
        initComponents();
                Image icon = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Imagenes/LOGO.png"));
       setIconImage(icon);
        setVisible(true);
        
        TablaApartados.setModel(a.ConsultaApartados());
        SumasMov suma=new SumasMov();
        totalprecios.setText("$"+suma.Suma_precioApartados());
        totalrefrendos.setText("$"+suma.Suma_refApartados());
        jPanel1.setOpaque(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        Fecha2 = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaApartados = new javax.swing.JTable();
        totalprecios = new javax.swing.JTextField();
        jLabel = new javax.swing.JLabel();
        totalrefrendos = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        Fecha1 = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        jButtonatras = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        fechaini = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        fechafin = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        empleado = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        cliente = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        articulo = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        refrendo = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        precio = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        estado = new javax.swing.JTextField();
        jLabelfondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Consulta reporte de compras");
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("al:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 30, 40, -1));

        Fecha2.setBackground(new java.awt.Color(96, 3, 3));
        getContentPane().add(Fecha2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 30, 110, -1));

        TablaApartados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        TablaApartados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaApartadosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TablaApartados);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 790, 370));

        totalprecios.setEditable(false);
        totalprecios.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(totalprecios, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 450, 110, -1));

        jLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel.setForeground(new java.awt.Color(255, 255, 255));
        jLabel.setText("Total de precios:");
        getContentPane().add(jLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 450, 120, -1));

        totalrefrendos.setEditable(false);
        totalrefrendos.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(totalrefrendos, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 450, 120, -1));

        jButton1.setBackground(new java.awt.Color(96, 3, 3));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("Aceptar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 30, -1, -1));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Fecha de reporte del:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 170, -1));

        Fecha1.setBackground(new java.awt.Color(96, 3, 3));
        getContentPane().add(Fecha1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 110, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Total de refendos:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 450, -1, -1));

        jButtonatras.setBackground(new java.awt.Color(96, 3, 3));
        jButtonatras.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonatras.setForeground(new java.awt.Color(255, 255, 255));
        jButtonatras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Go-back-icon (Custom).png"))); // NOI18N
        jButtonatras.setBorderPainted(false);
        jButtonatras.setContentAreaFilled(false);
        jButtonatras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonatrasActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonatras, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 20, -1, -1));

        jPanel1.setBackground(new java.awt.Color(0, 0, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("idApartado:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 90, 20));

        id.setEditable(false);
        id.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idActionPerformed(evt);
            }
        });
        jPanel1.add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 130, -1));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Fecha inicial:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 100, 20));

        fechaini.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        fechaini.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fechainiActionPerformed(evt);
            }
        });
        jPanel1.add(fechaini, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 130, -1));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Fecha final:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 90, 20));

        fechafin.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        fechafin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fechafinActionPerformed(evt);
            }
        });
        jPanel1.add(fechafin, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 130, -1));

        jLabel12.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("idEmpleado:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 90, 20));

        empleado.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        empleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empleadoActionPerformed(evt);
            }
        });
        jPanel1.add(empleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 130, -1));

        jLabel11.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("idCliente:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 80, 20));

        cliente.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clienteActionPerformed(evt);
            }
        });
        jPanel1.add(cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, 130, -1));

        jLabel14.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("idArticulo:");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 80, 20));

        articulo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        articulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                articuloActionPerformed(evt);
            }
        });
        jPanel1.add(articulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, 130, -1));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Refrendo:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 80, 20));

        refrendo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        refrendo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refrendoActionPerformed(evt);
            }
        });
        jPanel1.add(refrendo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 130, -1));

        jLabel10.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Precio Apartado:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 130, 20));

        precio.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        precio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                precioActionPerformed(evt);
            }
        });
        jPanel1.add(precio, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 130, -1));

        jButton2.setBackground(new java.awt.Color(96, 3, 3));
        jButton2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jButton2.setText("Modificar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, -1, -1));

        jLabel15.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Estado:");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, 80, 20));

        estado.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        estado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estadoActionPerformed(evt);
            }
        });
        jPanel1.add(estado, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, 130, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 80, 330, 350));

        jLabelfondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo (Medium).jpg"))); // NOI18N
        jLabelfondo.setText("jLabel1");
        getContentPane().add(jLabelfondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1150, 500));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        TablaApartados.setModel(a.ConsultaApartadosfecha(new SimpleDateFormat("yyyy-MM-dd").format(Fecha1.getDate()),new SimpleDateFormat("yyyy-MM-dd").format(Fecha2.getDate())));
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonatrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonatrasActionPerformed
        this.dispose();
        Consultar_Reporte  con_reporte=new Consultar_Reporte();
        con_reporte.setVisible(true);
    }//GEN-LAST:event_jButtonatrasActionPerformed

    private void idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idActionPerformed

    private void fechainiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fechainiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fechainiActionPerformed

    private void fechafinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fechafinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fechafinActionPerformed

    private void empleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empleadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_empleadoActionPerformed

    private void clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clienteActionPerformed

    private void articuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_articuloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_articuloActionPerformed

    private void refrendoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refrendoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_refrendoActionPerformed

    private void precioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_precioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_precioActionPerformed

    private void TablaApartadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaApartadosMouseClicked
        // TODO add your handling code here:
         int seleccion=TablaApartados.rowAtPoint(evt.getPoint());
         id.setText(String.valueOf(TablaApartados.getValueAt(seleccion, 0)));
         fechaini.setText(String.valueOf(TablaApartados.getValueAt(seleccion, 1)));
         fechafin.setText(String.valueOf(TablaApartados.getValueAt(seleccion, 2)));
         precio.setText(String.valueOf(TablaApartados.getValueAt(seleccion, 3)));
         refrendo.setText(String.valueOf(TablaApartados.getValueAt(seleccion, 4)));
         empleado.setText(String.valueOf(TablaApartados.getValueAt(seleccion, 5)));
         cliente.setText(String.valueOf(TablaApartados.getValueAt(seleccion, 6)));
         articulo.setText(String.valueOf(TablaApartados.getValueAt(seleccion, 7)));
         estado.setText(String.valueOf(TablaApartados.getValueAt(seleccion, 8)));
    }//GEN-LAST:event_TablaApartadosMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        ModificaMov m=new ModificaMov();
        SumasMov suma=new SumasMov();
        m.ModificaApartado(id.getText(), fechaini.getText(), fechafin.getText(), precio.getText(), refrendo.getText(), empleado.getText(), cliente.getText(), articulo.getText());
        TablaApartados.setModel(a.ConsultaApartados());
        totalprecios.setText("$"+suma.Suma_precioApartados());
        totalrefrendos.setText("$"+suma.Suma_refApartados());
    }//GEN-LAST:event_jButton2ActionPerformed

    private void estadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_estadoActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser Fecha1;
    private com.toedter.calendar.JDateChooser Fecha2;
    private javax.swing.JTable TablaApartados;
    public static javax.swing.JTextField articulo;
    public static javax.swing.JTextField cliente;
    public static javax.swing.JTextField empleado;
    public static javax.swing.JTextField estado;
    public static javax.swing.JTextField fechafin;
    public static javax.swing.JTextField fechaini;
    public static javax.swing.JTextField id;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonatras;
    private javax.swing.JLabel jLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelfondo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTextField precio;
    public static javax.swing.JTextField refrendo;
    private javax.swing.JTextField totalprecios;
    private javax.swing.JTextField totalrefrendos;
    // End of variables declaration//GEN-END:variables
}
