/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ConsultarReporte;

import java.awt.Image;
import java.awt.Toolkit;
import java.text.SimpleDateFormat;

/**
 *
 * @author Gerardo
 */
public class Reporteperdidas extends javax.swing.JFrame {

    /**
     * Creates new form Reportecompras
     */
    ConsultasMov a=new ConsultasMov();
    SumasMov b=new SumasMov();
    int sumaing,sumaeg;
    public Reporteperdidas() {
        initComponents();
                Image icon = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Imagenes/LOGO.png"));
       setIconImage(icon);
        setVisible(true);
        Tablaventas.setModel(a.ConsultaVentasid());
        Tablacompras.setModel(a.ConsultaComprasid());
        Tablarefemp.setModel(a.ConsultaEmpeñosrefid());
        Tablaprestemp.setModel(a.ConsultaEmpeñosprestid());
        jTable3.setModel(a.ConsultaEmpeñosfinid());
        jTable1.setModel(a.ConsultaApartadosid());
        sumaventas.setText(b.SumaVentas());
        sumarefemp.setText(b.Suma_refEmpeños());
        sumacompras.setText(b.SumaCompras());
        sumarefprest.setText(b.Suma_prestEmpeños());
        jTextField1.setText(b.Suma_refApartados());
        jTextField2.setText(b.Suma_finiemp());
        sumaing=(Integer.parseInt(sumaventas.getText()))+(Integer.parseInt(sumarefemp.getText())+Integer.parseInt(jTextField1.getText())+Integer.parseInt(jTextField2.getText()));
        Totalingresos.setText(String.valueOf(sumaing));
        sumaeg=(Integer.parseInt(sumacompras.getText())+(Integer.parseInt(sumarefprest.getText())));
        Totalegresos.setText(String.valueOf(sumaeg));
        sumafinal.setText(String.valueOf(sumaing-sumaeg));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonatras = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        Fecha2 = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tablaventas = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        Fecha1 = new com.toedter.calendar.JDateChooser();
        jScrollPane2 = new javax.swing.JScrollPane();
        Tablacompras = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        Tablaprestemp = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        Tablarefemp = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        sumaventas = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        sumarefemp = new javax.swing.JTextField();
        sumacompras = new javax.swing.JTextField();
        sumarefprest = new javax.swing.JTextField();
        Totalingresos = new javax.swing.JTextField();
        Totalegresos = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        sumafinal = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jLabelfondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ingresos y Egresos");
        setMaximumSize(new java.awt.Dimension(1230, 540));
        setMinimumSize(new java.awt.Dimension(1230, 540));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonatras.setBackground(new java.awt.Color(96, 3, 3));
        jButtonatras.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButtonatras.setForeground(new java.awt.Color(255, 255, 255));
        jButtonatras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Go-back-icon (Custom).png"))); // NOI18N
        jButtonatras.setBorderPainted(false);
        jButtonatras.setContentAreaFilled(false);
        jButtonatras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonatrasActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonatras, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("al:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, 40, -1));

        Fecha2.setBackground(new java.awt.Color(96, 3, 3));
        getContentPane().add(Fecha2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, 110, -1));

        Tablaventas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(Tablaventas);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 180, 270));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("Aceptar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 10, -1, -1));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Fecha de reporte del:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 170, -1));

        Fecha1.setBackground(new java.awt.Color(96, 3, 3));
        getContentPane().add(Fecha1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, 110, -1));

        Tablacompras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(Tablacompras);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 100, 170, 270));

        Tablaprestemp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(Tablaprestemp);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 100, 170, 270));

        Tablarefemp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane4.setViewportView(Tablarefemp);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, 180, 270));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Egresos");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 50, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Ingresos");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 50, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Compras");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 80, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Prestamos (Empeños)");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 80, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Ventas");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Renovaciones (Empeños)");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, -1, -1));

        sumaventas.setEditable(false);
        sumaventas.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        sumaventas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sumaventasActionPerformed(evt);
            }
        });
        getContentPane().add(sumaventas, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, 140, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("$");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("$");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 380, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("$");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 380, 10, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("$");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 380, 10, -1));

        sumarefemp.setEditable(false);
        sumarefemp.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        getContentPane().add(sumarefemp, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 380, 130, -1));

        sumacompras.setEditable(false);
        sumacompras.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        getContentPane().add(sumacompras, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 380, 120, -1));

        sumarefprest.setEditable(false);
        sumarefprest.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        getContentPane().add(sumarefprest, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 380, 120, -1));

        Totalingresos.setEditable(false);
        Totalingresos.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        getContentPane().add(Totalingresos, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 420, 120, -1));

        Totalegresos.setEditable(false);
        Totalegresos.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        getContentPane().add(Totalegresos, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 410, 120, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("$");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 420, -1, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("$");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 410, -1, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("+");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 380, -1, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("=");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 420, -1, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("+");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 380, -1, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("=");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 410, -1, -1));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Ingresos - Egresos =");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 470, -1, -1));

        sumafinal.setEditable(false);
        sumafinal.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        getContentPane().add(sumafinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 470, 100, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane5.setViewportView(jTable1);

        getContentPane().add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 100, 170, 270));

        jTextField1.setEditable(false);
        jTextField1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 380, 100, -1));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("+      $");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 380, -1, -1));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("+       $");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 380, -1, -1));

        jTextField2.setEditable(false);
        jTextField2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 380, 120, -1));

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Apartados");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 80, 70, -1));

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 80, -1, -1));

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Finiquitos (Empeños)");
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 80, -1, -1));

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane7.setViewportView(jTable3);

        getContentPane().add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 100, 170, 270));

        jLabelfondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo (Medium).jpg"))); // NOI18N
        jLabelfondo.setMaximumSize(new java.awt.Dimension(1230, 540));
        jLabelfondo.setMinimumSize(new java.awt.Dimension(1230, 540));
        jLabelfondo.setPreferredSize(new java.awt.Dimension(1230, 540));
        getContentPane().add(jLabelfondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1230, 540));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonatrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonatrasActionPerformed
       this.dispose();
       Consultar_Reporte  con_reporte=new Consultar_Reporte();
       con_reporte.setVisible(true);
    }//GEN-LAST:event_jButtonatrasActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Tablaventas.setModel(a.ConsultaVentasidfecha(new SimpleDateFormat("yyyy-MM-dd").format(Fecha1.getDate()),new SimpleDateFormat("yyyy-MM-dd").format(Fecha2.getDate())));
        Tablacompras.setModel(a.ConsultaComprasidfecha(new SimpleDateFormat("yyyy-MM-dd").format(Fecha1.getDate()),new SimpleDateFormat("yyyy-MM-dd").format(Fecha2.getDate())));
        Tablarefemp.setModel(a.ConsultaEmpeñosrefidfecha(new SimpleDateFormat("yyyy-MM-dd").format(Fecha1.getDate()),new SimpleDateFormat("yyyy-MM-dd").format(Fecha2.getDate())));
        Tablaprestemp.setModel(a.ConsultaEmpeñosprestidfecha(new SimpleDateFormat("yyyy-MM-dd").format(Fecha1.getDate()),new SimpleDateFormat("yyyy-MM-dd").format(Fecha2.getDate())));
        jTable3.setModel(a.ConsultaEmpeñosfinidfecha(new SimpleDateFormat("yyyy-MM-dd").format(Fecha1.getDate()),new SimpleDateFormat("yyyy-MM-dd").format(Fecha2.getDate())));
        jTable1.setModel(a.ConsultaApartadosidFecha(new SimpleDateFormat("yyyy-MM-dd").format(Fecha1.getDate()),new SimpleDateFormat("yyyy-MM-dd").format(Fecha2.getDate())));
        sumaventas.setText(b.SumaVentasfecha(new SimpleDateFormat("yyyy-MM-dd").format(Fecha1.getDate()),new SimpleDateFormat("yyyy-MM-dd").format(Fecha2.getDate())));
        sumarefemp.setText(b.Suma_refEmpeñosfecha(new SimpleDateFormat("yyyy-MM-dd").format(Fecha1.getDate()),new SimpleDateFormat("yyyy-MM-dd").format(Fecha2.getDate())));
        sumacompras.setText(b.SumaComprasfecha(new SimpleDateFormat("yyyy-MM-dd").format(Fecha1.getDate()),new SimpleDateFormat("yyyy-MM-dd").format(Fecha2.getDate())));
        sumarefprest.setText(b.Suma_prestEmpeñosfecha(new SimpleDateFormat("yyyy-MM-dd").format(Fecha1.getDate()),new SimpleDateFormat("yyyy-MM-dd").format(Fecha2.getDate())));
        jTextField1.setText(b.Suma_precioApartadosfecha(new SimpleDateFormat("yyyy-MM-dd").format(Fecha1.getDate()),new SimpleDateFormat("yyyy-MM-dd").format(Fecha2.getDate())));
        jTextField2.setText(b.Suma_finiempfecha(new SimpleDateFormat("yyyy-MM-dd").format(Fecha1.getDate()),new SimpleDateFormat("yyyy-MM-dd").format(Fecha2.getDate())));
        sumaing=(Integer.parseInt(sumaventas.getText()))+(Integer.parseInt(sumarefemp.getText())+Integer.parseInt(jTextField1.getText())+Integer.parseInt(jTextField2.getText()));
        Totalingresos.setText(String.valueOf(sumaing));
        sumaeg=(Integer.parseInt(sumacompras.getText())+(Integer.parseInt(sumarefprest.getText())));
        Totalegresos.setText(String.valueOf(sumaeg));
        sumafinal.setText(String.valueOf(sumaing-sumaeg));
    }//GEN-LAST:event_jButton1ActionPerformed

    private void sumaventasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sumaventasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sumaventasActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser Fecha1;
    private com.toedter.calendar.JDateChooser Fecha2;
    private javax.swing.JTable Tablacompras;
    private javax.swing.JTable Tablaprestemp;
    private javax.swing.JTable Tablarefemp;
    private javax.swing.JTable Tablaventas;
    private javax.swing.JTextField Totalegresos;
    private javax.swing.JTextField Totalingresos;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonatras;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelfondo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField sumacompras;
    private javax.swing.JTextField sumafinal;
    private javax.swing.JTextField sumarefemp;
    private javax.swing.JTextField sumarefprest;
    private javax.swing.JTextField sumaventas;
    // End of variables declaration//GEN-END:variables
}
