/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ConsultarCliente;

import casadeempeños.Pantalla_bienvenido;
import java.awt.*;

import javax.swing.*;


public class AgregarCuenta extends javax.swing.JFrame {

    /**
     * Creates new form AgregarCuenta
     */
  
    Manejocuentas mn;
    public AgregarCuenta() {
        initComponents();
         this.setLocationRelativeTo(null);
        marcar.setVisible(false);
                Image icon = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Imagenes/LOGO.png"));
       setIconImage(icon);
        setVisible(true);
        jPanel2.setOpaque(false);
        mn=new Manejocuentas();
        tablaemp.setModel(mn.Consultartodas());
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldusuario = new javax.swing.JTextField();
        contraseña = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        confirmacontraseña = new javax.swing.JPasswordField();
        marcar = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaemp = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        idCon = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        tipo_acceso = new javax.swing.JComboBox();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        acceso = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        nombre = new javax.swing.JTextField();
        id = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        contra1 = new javax.swing.JTextField();
        jLabelfondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1130, 500));
        setMinimumSize(new java.awt.Dimension(1130, 500));
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(1130, 500));
        getContentPane().setLayout(null);

        jPanel1.setMaximumSize(new java.awt.Dimension(1130, 500));
        jPanel1.setMinimumSize(new java.awt.Dimension(1130, 500));
        jPanel1.setPreferredSize(new java.awt.Dimension(1130, 500));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nombre del usuario");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 160, -1));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Contraseña:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 140, -1));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Tipo de acceso");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 150, -1));

        jTextFieldusuario.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel1.add(jTextFieldusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, 110, -1));

        contraseña.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel1.add(contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 110, -1));

        jButton1.setBackground(new java.awt.Color(96, 3, 3));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("Aceptar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 110, 90, -1));

        jButton2.setBackground(new java.awt.Color(96, 3, 3));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setText("Limpiar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 70, 90, -1));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Confirmar contraseña");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 160, -1));

        confirmacontraseña.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel1.add(confirmacontraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 110, -1));

        marcar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        marcar.setForeground(new java.awt.Color(255, 255, 255));
        marcar.setText("*");
        jPanel1.add(marcar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 130, 10, -1));

        jButton3.setBackground(new java.awt.Color(96, 3, 3));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Go-back-icon (Custom).png"))); // NOI18N
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 10, 50, -1));

        tablaemp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tablaemp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaempMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaemp);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 740, 220));

        jButton4.setBackground(new java.awt.Color(96, 3, 3));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton4.setText("Consultar todas las cuentas");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 210, -1, -1));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Crear Cuenta: ");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Hacer Consulta o Eliminar ");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 30, -1, -1));

        jLabel9.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("idCuenta: ");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 70, -1, -1));

        idCon.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        idCon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idConActionPerformed(evt);
            }
        });
        jPanel1.add(idCon, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 70, 90, -1));

        jButton5.setBackground(new java.awt.Color(96, 3, 3));
        jButton5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton5.setText("Consultar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 100, -1, -1));

        jButton6.setBackground(new java.awt.Color(96, 3, 3));
        jButton6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton6.setText("Eliiminar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 100, -1, -1));

        tipo_acceso.setBackground(new java.awt.Color(96, 3, 3));
        tipo_acceso.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tipo_acceso.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Administrador", "Empleado" }));
        jPanel1.add(tipo_acceso, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, 120, -1));

        jPanel2.setBackground(new java.awt.Color(96, 3, 3));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Nombre del usuario");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 160, -1));

        acceso.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel2.add(acceso, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 110, -1));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Contraseña:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 140, -1));

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Tipo de acceso");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 150, -1));

        jButton7.setBackground(new java.awt.Color(96, 3, 3));
        jButton7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton7.setText("Modificar");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 100, -1));

        nombre.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel2.add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, 110, -1));

        id.setEditable(false);
        id.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel2.add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, 110, -1));

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("idEmpleado");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 160, -1));

        contra1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jPanel2.add(contra1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 110, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 250, 330, 200));

        jLabelfondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo (Medium).jpg"))); // NOI18N
        jLabelfondo.setMaximumSize(new java.awt.Dimension(1130, 500));
        jLabelfondo.setMinimumSize(new java.awt.Dimension(1130, 500));
        jLabelfondo.setPreferredSize(new java.awt.Dimension(1130, 500));
        jPanel1.add(jLabelfondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1130, 500));

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1130, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        String id;
        id=idCon.getText();
        mn=new Manejocuentas();
        mn.Eliminacuenta(id);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        mn=new Manejocuentas();
        tablaemp.setModel(mn.mostrarconsulta(idCon.getText()));
    }//GEN-LAST:event_jButton5ActionPerformed

    private void idConActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idConActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idConActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        mn=new Manejocuentas();
        tablaemp.setModel(mn.Consultartodas());
        mn=null;
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        AgregarCuenta.this.dispose();
        Pantalla_bienvenido pbien = new Pantalla_bienvenido();
        pbien.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        jTextFieldusuario.setText(null);
        contraseña.setText(null);
        confirmacontraseña.setText(null);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String nombre;
        char[] cont,cont1;
        String contra,contraconfirm;
        String tipo ;
        mn=new Manejocuentas();

        cont=contraseña.getPassword();
        cont1=confirmacontraseña.getPassword();

        nombre=jTextFieldusuario.getText();
        tipo=String.valueOf(tipo_acceso.getSelectedItem());
        contra=new String(cont);
        contraconfirm=new String(cont1);
        if(!contra.equals(contraconfirm)|("".equals(nombre)|"".equals(contra)|"".equals(tipo))){
            JOptionPane.showMessageDialog(null,"Las contraseñas no coinciden o le faltó llenar algún dato");
        }
        else
        if(contra.length()>8){
            marcar.setVisible(true);
            JOptionPane.showMessageDialog(null,"La contraseña debe ser de 8 caracteres maximo");
        }
        else {

            mn.Insertarcuenta(nombre,tipo,contra);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tablaempMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaempMouseClicked
        // TODO add your handling code here:
        int seleccion=tablaemp.rowAtPoint(evt.getPoint());
        id.setText(String.valueOf(tablaemp.getValueAt(seleccion, 0)));
        nombre.setText(String.valueOf(tablaemp.getValueAt(seleccion, 1)));
        contra1.setText(String.valueOf(tablaemp.getValueAt(seleccion, 2)));
        acceso.setText(String.valueOf(tablaemp.getValueAt(seleccion, 3)));
    }//GEN-LAST:event_tablaempMouseClicked

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        mn=new Manejocuentas();
        mn.ActualizaCuenta(id.getText(), nombre.getText(), contra1.getText(), acceso.getText());
         tablaemp.setModel(mn.Consultartodas());
        
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField acceso;
    private javax.swing.JPasswordField confirmacontraseña;
    private javax.swing.JTextField contra1;
    private javax.swing.JPasswordField contraseña;
    private javax.swing.JTextField id;
    private javax.swing.JTextField idCon;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelfondo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextFieldusuario;
    private javax.swing.JLabel marcar;
    private javax.swing.JTextField nombre;
    private javax.swing.JTable tablaemp;
    private javax.swing.JComboBox tipo_acceso;
    // End of variables declaration//GEN-END:variables
}
